### ISSUE TITLE
cannot import name Merge

### ISSUE THREAD

**Issue by MarcosGrzeca** [viniciusmss/Hate-Compare#1]
Traceback (most recent call last):
  File "cnn.py", line 6, in <module>
    from keras.layers import Activation, Dense, Dropout, Embedding, Flatten, Input, Merge, Convolution1D, MaxPooling1D, GlobalMaxPooling1D
ImportError: cannot import name Merge

**Comment by viniciusmss** [comment]
Hi Marcos,

Keras deprecated Merge at some point. To be able to use it, you'll have to install version 1.2.2. If you're using anaconda, the environment's .yml file is available [here](https://gist.github.com/viniciusmss/9607b78d0de00f1417cee18f3fa5a2a0).

Let me know if you come across any other issues.
